### ISSUE TITLE
TUC-Forum

### ISSUE THREAD

**Issue by joshuajeschek** [top-22/docs#1]
# Thema: TU-Chemnitz-Forum

## Hintergrund
Es wird sich viel um die Verbindung von Studenten in Präsenz gekümmert, allerdings haben wir durch die Corona-Pandemie gelernt, wie schnell der Kontakt in Präsenz wegfallen kann. Neben diesem Aspekt spielt auch das heutige digitale Zeitalter eine Rolle. Jeder besitzt ein Smartphone und hat somit Zugriff auf das Internet. Folglich wäre ein zentrales Forum für alle Studenten der TU-Chemnitz eine Möglichkeit sich in Kontakt zu setzen, sich über Events zu informieren, Gruppen für Projekte zu bilden, als auch sich mit Kommilitonen über Themen in dem Studiengang auszutauschen, ohne dass diese nach einem Semester für andere Studierende verloren gehen (Opal).

## Funktionsumfang
- zentrale Startseite mit Beiträgen über Möglichkeiten sich mit anderen Studierenden in Verbindung zu setzen (z.B. aktuelle Events an der TU-Chemnitz)
- Ein sich ganz oben befindender angepinnter Beitrag, welche wie ein Live-Chat funktioniert, um sich mit Studierenden auszutauschen
- Eventuell Aufteilung in verschiedene Bereich wie: "Aktuell", "Studiengang", "Module" und dazugehörige Informationen
- Eventuell einen "Hilfe-Bereich" wo zentral alles Wichtige von Funktionen der TU-Chemnitz für Studenten zusammengefasst ist
- Wenn möglich einen Zugang mittel TUC-Login, um nur Studenten der TU-Chemnitz Zugang zu gewähren

## Umsetzung
- als Webapp -> unabhängig vom genutzten Gerät
- Frameworks (noch in Besprechung) -> z.B React
- Prototyping: Figma oder https://penpot.app/
- ToDo / Note Bereich: ...

**Comment by ghost** [comment]
# Meeting 28.11.2022 - Penpot Prototypen
## Vorstellung Ergebnisse
### Justin
- Angelehnt an Foraum.de
- Oben eine Auswahl mit HOME und MODUL
- KEINEN Studiengang, da nicht sinnvoll
- Bestimmte Module an Login binden, oder wenigstens die Vorschläge, die zu deinem Studium passen
- Mittig auf der Homeseite Highlights (u.a. Live-Chats)
- Chat-Filter wären notwendig
- unten am Anhang verteilte Nachrichten aus verschiedenen Foren
- später eventuell angepasst an die Interessen der Nutzer
- Favoriten-Foren selbst anpassbar (OPAL angelehnt)

### Joni
- leichtes Design
- Login mit anklicken auf Name für weitere Einstellungen
- Hilfe/Datenschutz/Impressum ganz am Ende der Website
- Labels zum Kategorisieren 
- Events werden mit den wichtigsten Daten bestückt
- Uhrzeiten (Start, Ende)
    
### Josh
- Räumen denen man joint (angelehnt Element)
- Beispiele für Räume 
- für alle in der TUC
- alle aus der angewandten Informatik
- Studenten der AI
- Angewandte Informatik des Anfangsjahres WS20
- Funktionale Programmierung für Studenten der AI
- Strukturell ein Baum
- in Räumen gibt es dann Posts (siehe Reddit / DC)
- Indikatoren von Chats für Audios und Dateien
- Plus Button für neue Posts
- Funktionalität um Textnachrichten abzusenden
- Aber auch um Dateien und Sprachnachrichten abzusenden
- Überposts könnten mehrere Kategorien oder keine enthalten (0..*)

#### Kritik
- nicht Mobilfähig durch zu verschachtelt 
- Lösung
  - Viele Fachbegriffe aus MCI2 xd
  - eigentlich: ist wirklich anpassbar, war nur nicht das Format des Entwurfs

### Philip
- Mix aus Josh und Justins Ideen
- Topbar mit (Forum, News, Icon der Seite, Search und Login)
- Search als Zeile, welche unter der Topbar auftaucht 
- Einstellbarkeit des Homescreens 
- Freundesanzeige (Philips ist leer)
- Entdeckung: TUC-Iconpack 
- Josh findet sie aber nicht schön
- findet Bootsrap Icons und Font Awesome Icons besser
- Akzentfarbe Grün wird positiv aufgenommen


### Sarah:
- Startseite: Zusammenfassung von allem Möglichen
- Neuigkeiten von deinen Abonnieren Zeug (Einstellbar)
- Übersicht über Kategorien
- WERBUNG 

---

## Bewertung Vorstellung
### Justin
- Dateien und Sprachnachrichten, Symbole
- Hauptseite selbst zusammenstellbar

### Josh
- Customisable
- Sehen was los ist/ Zurgiff aus Events (Event-Tag)
- Neugigkeiten in einer Liste

### Philip
- Simples Designes (Funktionabel) Projekt nicht zu Komplex, portierbarkeit betrachten
- Labels zum Kategoriesieren (siehe Reddit Flair)
- Remember me auf der Seite

### Joni
- Top bar (CH3OH wenn schon denn schon [Im legaly Blind]) bzw. side menu

### Sarah
- Event übersicht

### Tom
- einfach mal was machen und es dann wegschmeißen 

---

## Entscheidung für Josh
### Ideen
- Topbar 
- Login mit TUC
- Kategorisierung mit Flairs
- Searchbar
- Mit verschiedenen Modi siehe Josh
- Räume anpinnbar

### Eventuell:
- Eventseite extra
- Neuigkeiten 

### Screen:
- Homescreen
- Forumscreen
- Chatscreen
- Login-Drop-Down

---

## Aufgaben für nächstes Meeting 05.12.2022
- Sarah:
  - Login
- Justin:
  - Profil
- Joshua:
  - Homescreen und Room-Lookup
- Philip:
  - Roomdetails
- Tom:
  - Thread Create
- Joni:
  - Thread

**Comment by joshuajeschek** [comment]
# Meeting 05.12.2022 - Penpot Prototyp der gesamten Anwendung
## Vorstellung Ergebnisse
- relativ unspektakulär, da aufeinander angepasst
- Kleinigkeiten zu bemängeln, die beim Programmieren dann so oder so aufgefallen wären

---

## Bemerkungen zum Design
- Einheitlicher Create Button
  - damit einher gehen einheitliche Icons
- Einheitliche Topbar
- Nutzen des TUC - Logins
  - damit kann auf Login / Register Screen verzichtet werden, nur WTC Button
- Default-Ansicht = Gast (Keine extra loginseite)
  - Nur einsicht in Öfentlcihe Beiträge
- Josh nicht zufrieden mit Farbschema.
  - Erstmal irrelevant da wir es später einfach ändern können
  - 60:30:10 Regel beachten.

## Plan für nächste Woche
- Generell sind alle dazu aufgerufen sich mit Frameworks auseinanderzusetzen.
- Josh wird dann dazu noch einmal referieren.
- Es soll eine kleine Diskussion geben.
- Alle Meinungen sind willkommen.
- Im Endeffekt geht es darum das wir uns in dieser Woche auf ein Framework einigen.
  - beziehungsweise ein Tech Stack

**noch kein genauer Termin, aber eher als Montag wird angestrebt!**
(erschwerende Bedingungen da Josh mit seinem Englisch Vortrag zu tun hat)

**Comment by Rotwolf** [comment]
# Meeting 12.12.2022 - Frameworks/Techstacks

## Vorstellung von verschiedenen Frameworks/Stacks/Paketmanagern
* nextjs (React)
* postgres + pgadmin
* prisma
* bootstrap (mit Sass)
* yarn
* github actions

→ Einigung auf die Vorgestellten Frameworks/Stacks/Paketmanagern

## Plan für nächste Woche

### Treffen am Nachmittag des 14.12.2022
  * Josh & Philip erstellen eine Standartseite mit allen Frameworks 
    * Versuchen so viel wie möglich vorzubereiten (frameworks installieren + integrieren)
    * Webseite bietet Grundlage um dann weiterzuentwickeln
  * Alle sind Eingeladen um zu partizipieren & mitzuhelfen

### Generell 
* Alle sollen sich alle mit Typescript, React, (ggf. Bootstrap) beschäftigen
  * Grund:
    * um Wissensdifferenzen zwischen Teammitgliedern minimieren
    * um Grundlagen für die spätere Arbeit zu legen
  * yarn im eigenen Setup installieren
  * Idee: Selbst lokal eine Webseite aufsetzen (gern herumexperimentieren) 
    * siehe: create react app command

**Nächstes Teammeeting wieder am nächsten Montag, dem 19.12.2022**

**Comment by ghost** [comment]
# Meeting 14., 16. & 19.12.2022 - Aufbau & Einführung in Framework
## Einrichtung Datenbankzugriff
- Datenbanksprache:
  - [PostgreSQL](https://www.postgresql.org/)
- Einrichtung Zugriff auf Datenbank Web-Interface:
  - [pgAdmin](https://www.pgadmin.org/)
- Einrichtung Zugriff auf Datenbank über Tunnel zum Server
  - Host Datenbank auf localhost
  - Mittels [Cloudflared](https://github.com/cloudflare/cloudflared)

## Aufbau Framework (14.12.2022)
- Eintrichten und erste Grundlagen der Frameworks
  - Bootstrap
  - Next.js
  - Prisma
  - React

## Einführung in Bestandteile des Frameworks (16. & 19.12.2022)
### Prisma
- Aufbau und Nutzung `schema.prisma`
  - Hinzufügen von Tabellen & Attributen
- Beispielabfragen an Datenbank mittels Prisma
- Benutzung GUI von Prisma (Studio)

### Typescript/React
- Basics in Typescript und React
  - Beispielseite mit Beispieldaten
  - Tricks & Tipps

### Bootstrap
- Nutzung Bootstrap mit
  - Templates
  - Sass

## To do's für's nächste Treffen (kein Datum)
- Erweitern Funktionalität um Benutzer eines spezifischen Raums anzuzeigen
- dann sollen Fragen geklärt werden, weitere Vorgehensweise geplant werden und über das Datenbankschema geplaudert werden

**Comment by joshuajeschek** [comment]
Moved this to [Projects](https://github.com/orgs/top-22/projects/1/views/4)
